# ==== PROMETHEUS ALERT RULES ====
# This file defines alerting rules for Prometheus.

groups:
  - name: example-alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP 5xx error rate on {{ $labels.instance }}"
          description: "More than 5% of HTTP requests are failing with 5xx errors on {{ $labels.instance }}." 