# ==== GRAFANA DATASOURCE: JAEGER ====
# This file configures Jaeger as a datasource for Grafana.

apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686
    access: proxy
    isDefault: false 