apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: tabularasa_prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686
    access: proxy
    isDefault: false 