spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tabularasadb
    username: tabulauser
    password: tabulapass
  kafka:
    bootstrap-servers: localhost:19092
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  security:
    enabled: true
    roles: ACTUATOR 